openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API для керування контактами і авторизації
tags:
  - name: Contacts
    description: Операції з контактами
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /contacts:
    get: 
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    delete: 
      $ref: ../swagger/paths/contacts/{Id}/delete.yaml
    get:
      $ref: ../swagger/paths/contacts/{Id}/get.yaml
    patch: 
      $ref: ../swagger/paths/contacts/{Id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
